const rawData = [
    // ==========================================
    // 【1. 技術・AMJ専門 (半導体・メンテナンス・製造)】
    // ==========================================
    {en: "Semiconductor", jp: "半導体", cat: "技術"},
    {en: "Wafer", jp: "ウェハー", cat: "技術"},
    {en: "Chamber", jp: "真空室/チャンバー", cat: "技術"},
    {en: "Vacuum", jp: "真空", cat: "技術"},
    {en: "Deposition", jp: "堆積/成膜", cat: "技術"},
    {en: "Etching", jp: "エッチング", cat: "技術"},
    {en: "Lithography", jp: "リソグラフィ/露光", cat: "技術"},
    {en: "Yield", jp: "歩留まり", cat: "技術"},
    {en: "Throughput", jp: "処理能力/スループット", cat: "技術"},
    {en: "Cleanroom", jp: "クリーンルーム", cat: "技術"},
    {en: "Particle", jp: "微粒子/パーティクル", cat: "技術"},
    {en: "Contamination", jp: "汚染", cat: "技術"},
    {en: "Silicon", jp: "シリコン", cat: "技術"},
    {en: "Substrate", jp: "基板", cat: "技術"},
    {en: "Circuit", jp: "回路", cat: "技術"},
    {en: "Integrated Circuit", jp: "集積回路(IC)", cat: "技術"},
    {en: "Maintenance", jp: "保守/メンテナンス", cat: "技術"},
    {en: "Preventive", jp: "予防的な", cat: "技術"},
    {en: "Corrective", jp: "修正の/事後保全の", cat: "技術"},
    {en: "Inspection", jp: "検査", cat: "技術"},
    {en: "Calibration", jp: "校正/キャリブレーション", cat: "技術"},
    {en: "Installation", jp: "設置/インストール", cat: "技術"},
    {en: "Troubleshooting", jp: "トラブルシューティング", cat: "技術"},
    {en: "Diagnosis", jp: "診断", cat: "技術"},
    {en: "Equipment", jp: "装置/機器", cat: "技術"},
    {en: "Device", jp: "デバイス/装置", cat: "技術"},
    {en: "Component", jp: "部品/コンポーネント", cat: "技術"},
    {en: "Spare parts", jp: "予備部品", cat: "技術"},
    {en: "Consumables", jp: "消耗品", cat: "技術"},
    {en: "Inventory", jp: "在庫", cat: "技術"},
    {en: "Defect", jp: "欠陥", cat: "技術"},
    {en: "Malfunction", jp: "誤作動/故障", cat: "技術"},
    {en: "Breakdown", jp: "故障/内訳", cat: "技術"},
    {en: "Error code", jp: "エラーコード", cat: "技術"},
    {en: "Spec", jp: "仕様(Specification)", cat: "技術"},
    {en: "Tolerance", jp: "公差/許容範囲", cat: "技術"},
    {en: "Precision", jp: "精密さ", cat: "技術"},
    {en: "Accuracy", jp: "正確さ", cat: "技術"},
    {en: "Efficiency", jp: "効率", cat: "技術"},
    {en: "Reliability", jp: "信頼性", cat: "技術"},
    {en: "Durability", jp: "耐久性", cat: "技術"},
    {en: "Stability", jp: "安定性", cat: "技術"},
    {en: "Voltage", jp: "電圧", cat: "技術"},
    {en: "Current", jp: "電流", cat: "技術"},
    {en: "Resistance", jp: "抵抗", cat: "技術"},
    {en: "Conductivity", jp: "伝導性", cat: "技術"},
    {en: "Frequency", jp: "周波数/頻度", cat: "技術"},
    {en: "Temperature", jp: "温度", cat: "技術"},
    {en: "Humidity", jp: "湿度", cat: "技術"},
    {en: "Pressure", jp: "圧力", cat: "技術"},
    {en: "Sensor", jp: "センサー", cat: "技術"},
    {en: "Actuator", jp: "アクチュエータ/作動装置", cat: "技術"},
    {en: "Valve", jp: "バルブ/弁", cat: "技術"},
    {en: "Pump", jp: "ポンプ", cat: "技術"},
    {en: "Filter", jp: "フィルター", cat: "技術"},
    {en: "Nozzle", jp: "ノズル", cat: "技術"},
    {en: "Robot arm", jp: "ロボットアーム", cat: "技術"},
    {en: "Load port", jp: "ロードポート", cat: "技術"},
    {en: "Manual", jp: "マニュアル/手動の", cat: "技術"},
    {en: "Procedure", jp: "手順", cat: "技術"},
    {en: "Protocol", jp: "手順/規約", cat: "技術"},
    {en: "Instruction", jp: "指示/説明書", cat: "技術"},
    {en: "Guideline", jp: "指針/ガイドライン", cat: "技術"},
    {en: "Regulation", jp: "規制/規則", cat: "技術"},
    {en: "Compliance", jp: "法令順守", cat: "技術"},
    {en: "Safety", jp: "安全", cat: "技術"},
    {en: "Hazard", jp: "危険", cat: "技術"},
    {en: "Precaution", jp: "予防策", cat: "技術"},
    {en: "Emergency", jp: "緊急事態", cat: "技術"},
    {en: "Evacuation", jp: "避難", cat: "技術"},
    {en: "Toxic", jp: "有毒な", cat: "技術"},
    {en: "Flammable", jp: "可燃性の", cat: "技術"},
    {en: "Chemical", jp: "化学物質", cat: "技術"},
    {en: "Gas", jp: "ガス", cat: "技術"},
    {en: "Liquid", jp: "液体", cat: "技術"},
    {en: "Plasma", jp: "プラズマ", cat: "技術"},
    {en: "Layer", jp: "層", cat: "技術"},
    {en: "Surface", jp: "表面", cat: "技術"},
    {en: "Diameter", jp: "直径", cat: "技術"},
    {en: "Thickness", jp: "厚さ", cat: "技術"},
    {en: "Measurement", jp: "測定", cat: "技術"},
    {en: "Analysis", jp: "分析", cat: "技術"},
    {en: "Data", jp: "データ", cat: "技術"},
    {en: "Log", jp: "記録/ログ", cat: "技術"},
    {en: "Upgrade", jp: "アップグレード", cat: "技術"},
    {en: "Modify", jp: "修正する/改造する", cat: "技術"},
    {en: "Replace", jp: "交換する", cat: "技術"},
    {en: "Repair", jp: "修理する", cat: "技術"},
    {en: "Fix", jp: "直す/固定する", cat: "技術"},
    {en: "Assemble", jp: "組み立てる", cat: "技術"},
    {en: "Dismantle", jp: "分解する", cat: "技術"},
    {en: "Connect", jp: "接続する", cat: "技術"},
    {en: "Disconnect", jp: "切断する", cat: "技術"},
    {en: "Configure", jp: "設定する/構成する", cat: "技術"},
    {en: "Initialize", jp: "初期化する", cat: "技術"},
    {en: "Reboot", jp: "再起動する", cat: "技術"},
    {en: "Shut down", jp: "停止する", cat: "技術"},
    {en: "Activate", jp: "作動させる", cat: "技術"},
    {en: "Deactivate", jp: "停止させる", cat: "技術"},
    {en: "Monitor", jp: "監視する", cat: "技術"},
    {en: "Observe", jp: "観察する", cat: "技術"},
    {en: "Verify", jp: "検証する/確かめる", cat: "技術"},
    {en: "Validate", jp: "妥当性を確認する", cat: "技術"},
    {en: "Optimize", jp: "最適化する", cat: "技術"},
    {en: "Improve", jp: "改善する", cat: "技術"},
    {en: "Enhance", jp: "向上させる", cat: "技術"},
    {en: "Reduce", jp: "減らす", cat: "技術"},
    {en: "Increase", jp: "増やす", cat: "技術"},
    {en: "Minimize", jp: "最小限にする", cat: "技術"},
    {en: "Maximize", jp: "最大限にする", cat: "技術"},
    {en: "Automate", jp: "自動化する", cat: "技術"},
    {en: "Manufacture", jp: "製造する", cat: "技術"},
    {en: "Process", jp: "工程/処理する", cat: "技術"},
    {en: "Output", jp: "出力/生産高", cat: "技術"},
    {en: "Input", jp: "入力", cat: "技術"},
    {en: "Status", jp: "状態/ステータス", cat: "技術"},
    {en: "Condition", jp: "条件/状態", cat: "技術"},
    {en: "Solution", jp: "解決策/溶液", cat: "技術"},
    {en: "Function", jp: "機能", cat: "技術"},
    {en: "Feature", jp: "特徴", cat: "技術"},
    {en: "Prototype", jp: "試作品", cat: "技術"},
    {en: "Blueprint", jp: "設計図", cat: "技術"},
    {en: "Schematic", jp: "回路図", cat: "技術"},
    {en: "Diagram", jp: "図表", cat: "技術"},
    {en: "Chart", jp: "図/グラフ", cat: "技術"},
    {en: "Graph", jp: "グラフ", cat: "技術"},
    {en: "Parameter", jp: "媒介変数/パラメータ", cat: "技術"},
    {en: "Variable", jp: "変数", cat: "技術"},
    {en: "Constant", jp: "定数", cat: "技術"},
    {en: "Average", jp: "平均", cat: "技術"},
    {en: "Maximum", jp: "最大", cat: "技術"},
    {en: "Minimum", jp: "最小", cat: "技術"},
    {en: "Limit", jp: "限界/制限", cat: "技術"},
    {en: "Range", jp: "範囲", cat: "技術"},
    {en: "Cycle", jp: "周期/サイクル", cat: "技術"},
    {en: "Interval", jp: "間隔", cat: "技術"},
    {en: "Duration", jp: "期間/継続時間", cat: "技術"},
    {en: "Phase", jp: "段階/フェーズ", cat: "技術"},
    {en: "Stage", jp: "段階", cat: "技術"},
    {en: "Step", jp: "工程/歩み", cat: "技術"},
    {en: "Method", jp: "方法", cat: "技術"},
    {en: "Technique", jp: "技術/手法", cat: "技術"},
    {en: "System", jp: "システム", cat: "技術"},
    {en: "Mechanism", jp: "仕組み/メカニズム", cat: "技術"},
    {en: "Structure", jp: "構造", cat: "技術"},
    {en: "Material", jp: "材料/素材", cat: "技術"},
    {en: "Substance", jp: "物質", cat: "技術"},
    {en: "Element", jp: "要素/元素", cat: "技術"},
    {en: "Property", jp: "特性/財産", cat: "技術"},
    {en: "Characteristic", jp: "特徴", cat: "技術"},
    {en: "Quality", jp: "品質", cat: "技術"},
    {en: "Quantity", jp: "数量", cat: "技術"},
    {en: "Volume", jp: "体積/音量", cat: "技術"},
    {en: "Weight", jp: "重量", cat: "技術"},
    {en: "Width", jp: "幅", cat: "技術"},
    {en: "Height", jp: "高さ", cat: "技術"},
    {en: "Depth", jp: "深さ", cat: "技術"},
    {en: "Dimension", jp: "寸法/次元", cat: "技術"},
    {en: "Scale", jp: "目盛り/規模", cat: "技術"},
    {en: "Unit", jp: "単位/ユニット", cat: "技術"},
    {en: "Standard", jp: "基準/標準", cat: "技術"},
    {en: "Criteria", jp: "基準(複数形)", cat: "技術"},
    {en: "Requirement", jp: "要件", cat: "技術"},
    {en: "Specification", jp: "仕様", cat: "技術"},
    {en: "Warranty", jp: "保証", cat: "技術"},
    {en: "Guarantee", jp: "保証する", cat: "技術"},
    {en: "Expiration", jp: "有効期限", cat: "技術"},
    {en: "Technical", jp: "技術的な", cat: "技術"},
    {en: "Mechanical", jp: "機械的な", cat: "技術"},
    {en: "Electrical", jp: "電気の", cat: "技術"},
    {en: "Electronic", jp: "電子の", cat: "技術"},
    {en: "Digital", jp: "デジタルの", cat: "技術"},
    {en: "Analog", jp: "アナログの", cat: "技術"},
    {en: "Wireless", jp: "無線の", cat: "技術"},
    {en: "Remote", jp: "遠隔の", cat: "技術"},
    {en: "Portable", jp: "携帯用の", cat: "技術"},
    {en: "Compatible", jp: "互換性のある", cat: "技術"},
    {en: "Internal", jp: "内部の", cat: "技術"},
    {en: "External", jp: "外部の", cat: "技術"},
    {en: "Primary", jp: "主要な/一次の", cat: "技術"},
    {en: "Secondary", jp: "二次的な", cat: "技術"},
    {en: "Initial", jp: "初期の", cat: "技術"},
    {en: "Final", jp: "最終的な", cat: "技術"},
    {en: "Temporary", jp: "一時的な", cat: "技術"},
    {en: "Permanent", jp: "恒久的な", cat: "技術"},
    {en: "Simultaneous", jp: "同時の", cat: "技術"},
    {en: "Consecutive", jp: "連続した", cat: "技術"},
    {en: "Random", jp: "無作為の", cat: "技術"},
    {en: "Specific", jp: "特定の/具体的な", cat: "技術"},

    // ==========================================
    // 【2. オフィス・ビジネス (TOEIC頻出・実務)】
    // ==========================================
    {en: "Department", jp: "部署", cat: "オフィス"},
    {en: "Personnel", jp: "人事/全職員", cat: "オフィス"},
    {en: "Human Resources", jp: "人事部(HR)", cat: "オフィス"},
    {en: "Accounting", jp: "経理", cat: "オフィス"},
    {en: "Sales", jp: "営業", cat: "オフィス"},
    {en: "Marketing", jp: "マーケティング", cat: "オフィス"},
    {en: "Research", jp: "研究", cat: "オフィス"},
    {en: "Development", jp: "開発", cat: "オフィス"},
    {en: "Administration", jp: "管理/総務", cat: "オフィス"},
    {en: "Executive", jp: "重役", cat: "オフィス"},
    {en: "CEO", jp: "最高経営責任者", cat: "オフィス"},
    {en: "Manager", jp: "課長/部長", cat: "オフィス"},
    {en: "Supervisor", jp: "上司/監督者", cat: "オフィス"},
    {en: "Subordinate", jp: "部下", cat: "オフィス"},
    {en: "Colleague", jp: "同僚", cat: "オフィス"},
    {en: "Coworker", jp: "同僚", cat: "オフィス"},
    {en: "Staff", jp: "職員", cat: "オフィス"},
    {en: "Employee", jp: "従業員", cat: "オフィス"},
    {en: "Employer", jp: "雇用主", cat: "オフィス"},
    {en: "Intern", jp: "実習生", cat: "オフィス"},
    {en: "Client", jp: "顧客(依頼人)", cat: "オフィス"},
    {en: "Customer", jp: "顧客(客)", cat: "オフィス"},
    {en: "Supplier", jp: "供給業者", cat: "オフィス"},
    {en: "Vendor", jp: "販売業者", cat: "オフィス"},
    {en: "Distributor", jp: "代理店/卸売業者", cat: "オフィス"},
    {en: "Headquarters", jp: "本社", cat: "オフィス"},
    {en: "Branch", jp: "支店", cat: "オフィス"},
    {en: "Subsidiary", jp: "子会社", cat: "オフィス"},
    {en: "Factory", jp: "工場", cat: "オフィス"},
    {en: "Plant", jp: "工場/プラント", cat: "オフィス"},
    {en: "Warehouse", jp: "倉庫", cat: "オフィス"},
    {en: "Meeting", jp: "会議", cat: "オフィス"},
    {en: "Conference", jp: "会議/大会", cat: "オフィス"},
    {en: "Seminar", jp: "セミナー", cat: "オフィス"},
    {en: "Workshop", jp: "ワークショップ", cat: "オフィス"},
    {en: "Presentation", jp: "プレゼン", cat: "オフィス"},
    {en: "Agenda", jp: "議題", cat: "オフィス"},
    {en: "Minutes", jp: "議事録", cat: "オフィス"},
    {en: "Proposal", jp: "提案書", cat: "オフィス"},
    {en: "Report", jp: "報告書", cat: "オフィス"},
    {en: "Memo", jp: "社内連絡", cat: "オフィス"},
    {en: "Notice", jp: "通知/掲示", cat: "オフィス"},
    {en: "Announcement", jp: "発表", cat: "オフィス"},
    {en: "Document", jp: "書類", cat: "オフィス"},
    {en: "File", jp: "ファイル", cat: "オフィス"},
    {en: "Contract", jp: "契約書", cat: "オフィス"},
    {en: "Agreement", jp: "合意書", cat: "オフィス"},
    {en: "Policy", jp: "方針/規定", cat: "オフィス"},
    {en: "Rule", jp: "規則", cat: "オフィス"},
    {en: "Regulation", jp: "規制", cat: "オフィス"},
    {en: "Budget", jp: "予算", cat: "オフィス"},
    {en: "Cost", jp: "費用", cat: "オフィス"},
    {en: "Expense", jp: "経費", cat: "オフィス"},
    {en: "Price", jp: "価格", cat: "オフィス"},
    {en: "Profit", jp: "利益", cat: "オフィス"},
    {en: "Revenue", jp: "収益", cat: "オフィス"},
    {en: "Loss", jp: "損失", cat: "オフィス"},
    {en: "Sales figures", jp: "売上高", cat: "オフィス"},
    {en: "Forecast", jp: "予測", cat: "オフィス"},
    {en: "Target", jp: "目標", cat: "オフィス"},
    {en: "Goal", jp: "目的/ゴール", cat: "オフィス"},
    {en: "Objective", jp: "目的/目標", cat: "オフィス"},
    {en: "Strategy", jp: "戦略", cat: "オフィス"},
    {en: "Plan", jp: "計画", cat: "オフィス"},
    {en: "Project", jp: "プロジェクト", cat: "オフィス"},
    {en: "Task", jp: "業務/タスク", cat: "オフィス"},
    {en: "Duty", jp: "義務/職務", cat: "オフィス"},
    {en: "Responsibility", jp: "責任", cat: "オフィス"},
    {en: "Deadline", jp: "締め切り", cat: "オフィス"},
    {en: "Schedule", jp: "予定", cat: "オフィス"},
    {en: "Appointment", jp: "約束/予約", cat: "オフィス"},
    {en: "Reservation", jp: "予約(席・部屋)", cat: "オフィス"},
    {en: "Itinerary", jp: "旅程", cat: "オフィス"},
    {en: "Arrangement", jp: "手配", cat: "オフィス"},
    {en: "Accommodation", jp: "宿泊施設", cat: "オフィス"},
    {en: "Transportation", jp: "輸送機関", cat: "オフィス"},
    {en: "Flight", jp: "フライト", cat: "オフィス"},
    {en: "Ticket", jp: "チケット", cat: "オフィス"},
    {en: "Visa", jp: "ビザ", cat: "オフィス"},
    {en: "Passport", jp: "パスポート", cat: "オフィス"},
    {en: "Currency", jp: "通貨", cat: "オフィス"},
    {en: "Exchange rate", jp: "為替レート", cat: "オフィス"},
    {en: "Invoice", jp: "請求書", cat: "オフィス"},
    {en: "Receipt", jp: "領収書", cat: "オフィス"},
    {en: "Bill", jp: "請求書/勘定", cat: "オフィス"},
    {en: "Check", jp: "小切手", cat: "オフィス"},
    {en: "Cash", jp: "現金", cat: "オフィス"},
    {en: "Credit card", jp: "クレジットカード", cat: "オフィス"},
    {en: "Bank account", jp: "銀行口座", cat: "オフィス"},
    {en: "Transfer", jp: "振込/転勤", cat: "オフィス"},
    {en: "Deposit", jp: "預金/手付金", cat: "オフィス"},
    {en: "Withdrawal", jp: "引き出し", cat: "オフィス"},
    {en: "Balance", jp: "残高", cat: "オフィス"},
    {en: "Tax", jp: "税金", cat: "オフィス"},
    {en: "Insurance", jp: "保険", cat: "オフィス"},
    {en: "Benefit", jp: "福利厚生/利益", cat: "オフィス"},
    {en: "Salary", jp: "給料", cat: "オフィス"},
    {en: "Wage", jp: "賃金", cat: "オフィス"},
    {en: "Bonus", jp: "ボーナス", cat: "オフィス"},
    {en: "Promotion", jp: "昇進/促進", cat: "オフィス"},
    {en: "Retirement", jp: "退職", cat: "オフィス"},
    {en: "Resignation", jp: "辞職", cat: "オフィス"},
    {en: "Recruitment", jp: "採用", cat: "オフィス"},
    {en: "Application", jp: "応募/申請", cat: "オフィス"},
    {en: "Resume", jp: "履歴書", cat: "オフィス"},
    {en: "Interview", jp: "面接", cat: "オフィス"},
    {en: "Candidate", jp: "候補者", cat: "オフィス"},
    {en: "Hire", jp: "雇う", cat: "オフィス"},
    {en: "Fire", jp: "解雇する", cat: "オフィス"},
    {en: "Layoff", jp: "一時解雇", cat: "オフィス"},
    {en: "Training", jp: "研修", cat: "オフィス"},
    {en: "Orientation", jp: "オリエンテーション", cat: "オフィス"},
    {en: "Mentor", jp: "指導者", cat: "オフィス"},
    {en: "Skill", jp: "技能", cat: "オフィス"},
    {en: "Ability", jp: "能力", cat: "オフィス"},
    {en: "Experience", jp: "経験", cat: "オフィス"},
    {en: "Knowledge", jp: "知識", cat: "オフィス"},
    {en: "Qualification", jp: "資格", cat: "オフィス"},
    {en: "Certificate", jp: "証明書", cat: "オフィス"},
    {en: "License", jp: "免許", cat: "オフィス"},
    {en: "Degree", jp: "学位", cat: "オフィス"},
    {en: "Education", jp: "教育", cat: "オフィス"},
    {en: "Signature", jp: "署名", cat: "オフィス"},
    {en: "Stamp", jp: "印鑑/切手", cat: "オフィス"},
    {en: "Envelope", jp: "封筒", cat: "オフィス"},
    {en: "Postage", jp: "郵便料金", cat: "オフィス"},
    {en: "Delivery", jp: "配達", cat: "オフィス"},
    {en: "Shipment", jp: "発送/積荷", cat: "オフィス"},
    {en: "Package", jp: "小包", cat: "オフィス"},
    {en: "Courier", jp: "宅配業者", cat: "オフィス"},
    {en: "Tracking", jp: "追跡", cat: "オフィス"},
    {en: "Logistics", jp: "物流", cat: "オフィス"},
    {en: "Supply chain", jp: "供給網", cat: "オフィス"},
    {en: "Demand", jp: "需要", cat: "オフィス"},
    {en: "Supply", jp: "供給", cat: "オフィス"},
    {en: "Market", jp: "市場", cat: "オフィス"},
    {en: "Competitor", jp: "競合他社", cat: "オフィス"},
    {en: "Consumer", jp: "消費者", cat: "オフィス"},
    {en: "Product", jp: "製品", cat: "オフィス"},
    {en: "Service", jp: "サービス", cat: "オフィス"},
    {en: "Quality", jp: "品質", cat: "オフィス"},
    {en: "Feedback", jp: "意見/反応", cat: "オフィス"},
    {en: "Complaint", jp: "苦情", cat: "オフィス"},
    {en: "Inquiry", jp: "問い合わせ", cat: "オフィス"},
    {en: "Suggestion", jp: "提案", cat: "オフィス"},
    {en: "Recommendation", jp: "推薦", cat: "オフィス"},
    {en: "Apology", jp: "謝罪", cat: "オフィス"},
    {en: "Refund", jp: "返金", cat: "オフィス"},
    {en: "Replacement", jp: "交換品", cat: "オフィス"},
    {en: "Warranty", jp: "保証", cat: "オフィス"},

    // ==========================================
    // 【3. 基礎・文法語 (TOEIC 550点突破の要)】
    // ==========================================
    {en: "Provide", jp: "提供する", cat: "基礎"},
    {en: "Consider", jp: "考慮する", cat: "基礎"},
    {en: "Include", jp: "含む", cat: "基礎"},
    {en: "Allow", jp: "許可する", cat: "基礎"},
    {en: "Require", jp: "要求する", cat: "基礎"},
    {en: "Suggest", jp: "提案する", cat: "基礎"},
    {en: "Decide", jp: "決定する", cat: "基礎"},
    {en: "Expect", jp: "期待する", cat: "基礎"},
    {en: "Offer", jp: "提供する/申し出る", cat: "基礎"},
    {en: "Explain", jp: "説明する", cat: "基礎"},
    {en: "Describe", jp: "描写する/説明する", cat: "基礎"},
    {en: "Prepare", jp: "準備する", cat: "基礎"},
    {en: "Create", jp: "創造する", cat: "基礎"},
    {en: "Develop", jp: "開発する", cat: "基礎"},
    {en: "Improve", jp: "改善する", cat: "基礎"},
    {en: "Increase", jp: "増やす", cat: "基礎"},
    {en: "Decrease", jp: "減らす", cat: "基礎"},
    {en: "Reduce", jp: "減らす", cat: "基礎"},
    {en: "Produce", jp: "生産する", cat: "基礎"},
    {en: "Receive", jp: "受け取る", cat: "基礎"},
    {en: "Accept", jp: "受け入れる", cat: "基礎"},
    {en: "Refuse", jp: "拒否する", cat: "基礎"},
    {en: "Reject", jp: "拒絶する", cat: "基礎"},
    {en: "Agree", jp: "同意する", cat: "基礎"},
    {en: "Disagree", jp: "反対する", cat: "基礎"},
    {en: "Discuss", jp: "話し合う", cat: "基礎"},
    {en: "Contact", jp: "連絡する", cat: "基礎"},
    {en: "Inform", jp: "知らせる", cat: "基礎"},
    {en: "Notify", jp: "通知する", cat: "基礎"},
    {en: "Remind", jp: "思い出させる", cat: "基礎"},
    {en: "Attend", jp: "出席する", cat: "基礎"},
    {en: "Participate", jp: "参加する", cat: "基礎"},
    {en: "Join", jp: "加わる", cat: "基礎"},
    {en: "Visit", jp: "訪問する", cat: "基礎"},
    {en: "Travel", jp: "旅行する/移動する", cat: "基礎"},
    {en: "Depart", jp: "出発する", cat: "基礎"},
    {en: "Arrive", jp: "到着する", cat: "基礎"},
    {en: "Return", jp: "戻る", cat: "基礎"},
    {en: "Stay", jp: "滞在する", cat: "基礎"},
    {en: "Live", jp: "住む", cat: "基礎"},
    {en: "Work", jp: "働く", cat: "基礎"},
    {en: "Study", jp: "勉強する", cat: "基礎"},
    {en: "Learn", jp: "学ぶ", cat: "基礎"},
    {en: "Understand", jp: "理解する", cat: "基礎"},
    {en: "Know", jp: "知っている", cat: "基礎"},
    {en: "Think", jp: "考える", cat: "基礎"},
    {en: "Believe", jp: "信じる", cat: "基礎"},
    {en: "Hope", jp: "望む", cat: "基礎"},
    {en: "Wish", jp: "願う", cat: "基礎"},
    {en: "Want", jp: "欲しい", cat: "基礎"},
    {en: "Need", jp: "必要とする", cat: "基礎"},
    {en: "Like", jp: "好む", cat: "基礎"},
    {en: "Love", jp: "愛する", cat: "基礎"},
    {en: "Hate", jp: "嫌う", cat: "基礎"},
    {en: "Enjoy", jp: "楽しむ", cat: "基礎"},
    {en: "Start", jp: "始める", cat: "基礎"},
    {en: "Begin", jp: "始める", cat: "基礎"},
    {en: "Finish", jp: "終える", cat: "基礎"},
    {en: "End", jp: "終わる", cat: "基礎"},
    {en: "Complete", jp: "完了する", cat: "基礎"},
    {en: "Continue", jp: "続ける", cat: "基礎"},
    {en: "Stop", jp: "止める", cat: "基礎"},
    {en: "Pause", jp: "一時停止する", cat: "基礎"},
    {en: "Wait", jp: "待つ", cat: "基礎"},
    {en: "Remain", jp: "残る/〜のままである", cat: "基礎"},
    {en: "Change", jp: "変える", cat: "基礎"},
    {en: "Move", jp: "動く", cat: "基礎"},
    {en: "Open", jp: "開ける", cat: "基礎"},
    {en: "Close", jp: "閉じる", cat: "基礎"},
    {en: "Buy", jp: "買う", cat: "基礎"},
    {en: "Sell", jp: "売る", cat: "基礎"},
    {en: "Pay", jp: "支払う", cat: "基礎"},
    {en: "Cost", jp: "費用がかかる", cat: "基礎"},
    {en: "Spend", jp: "費やす", cat: "基礎"},
    {en: "Save", jp: "保存する/節約する", cat: "基礎"},
    {en: "Earn", jp: "稼ぐ", cat: "基礎"},
    {en: "Win", jp: "勝つ", cat: "基礎"},
    {en: "Lose", jp: "負ける/失う", cat: "基礎"},
    {en: "Find", jp: "見つける", cat: "基礎"},
    {en: "Look", jp: "見る", cat: "基礎"},
    {en: "Watch", jp: "見る(動くものを)", cat: "基礎"},
    {en: "See", jp: "見える/会う", cat: "基礎"},
    {en: "Hear", jp: "聞こえる", cat: "基礎"},
    {en: "Listen", jp: "聞く", cat: "基礎"},
    {en: "Touch", jp: "触れる", cat: "基礎"},
    {en: "Feel", jp: "感じる", cat: "基礎"},
    {en: "Smell", jp: "匂いがする", cat: "基礎"},
    {en: "Taste", jp: "味がする", cat: "基礎"},
    {en: "Eat", jp: "食べる", cat: "基礎"},
    {en: "Drink", jp: "飲む", cat: "基礎"},
    {en: "Sleep", jp: "眠る", cat: "基礎"},
    {en: "Wake", jp: "目覚める", cat: "基礎"},
    {en: "Wear", jp: "着ている", cat: "基礎"},
    {en: "Carry", jp: "運ぶ", cat: "基礎"},
    {en: "Bring", jp: "持ってくる", cat: "基礎"},
    {en: "Take", jp: "連れて行く/取る", cat: "基礎"},
    {en: "Put", jp: "置く", cat: "基礎"},
    {en: "Set", jp: "セットする", cat: "基礎"},
    {en: "Hold", jp: "持つ/開催する", cat: "基礎"},
    {en: "Keep", jp: "保つ", cat: "基礎"},
    {en: "Let", jp: "〜させる", cat: "基礎"},
    {en: "Make", jp: "作る/〜させる", cat: "基礎"},
    {en: "Do", jp: "する", cat: "基礎"},
    {en: "Go", jp: "行く", cat: "基礎"},
    {en: "Come", jp: "来る", cat: "基礎"},
    {en: "Have", jp: "持っている", cat: "基礎"},
    {en: "Be", jp: "〜である", cat: "基礎"},
    {en: "Can", jp: "〜できる", cat: "基礎"},
    {en: "Will", jp: "〜だろう", cat: "基礎"},
    {en: "Should", jp: "〜すべきだ", cat: "基礎"},
    {en: "Must", jp: "〜しなければならない", cat: "基礎"},
    {en: "May", jp: "〜かもしれない", cat: "基礎"},
    {en: "Might", jp: "〜かもしれない", cat: "基礎"},
    {en: "Could", jp: "〜できた/〜かもしれない", cat: "基礎"},
    {en: "Would", jp: "〜だろう", cat: "基礎"},
    {en: "However", jp: "しかしながら", cat: "基礎"},
    {en: "Therefore", jp: "したがって", cat: "基礎"},
    {en: "Although", jp: "〜だけれども", cat: "基礎"},
    {en: "Though", jp: "〜だけれども", cat: "基礎"},
    {en: "Unless", jp: "〜でない限り", cat: "基礎"},
    {en: "If", jp: "もし〜なら", cat: "基礎"},
    {en: "Because", jp: "なぜなら", cat: "基礎"},
    {en: "Since", jp: "〜なので/〜以来", cat: "基礎"},
    {en: "As", jp: "〜として/〜なので", cat: "基礎"},
    {en: "While", jp: "〜の間/〜だが", cat: "基礎"},
    {en: "When", jp: "〜の時", cat: "基礎"},
    {en: "Before", jp: "〜の前に", cat: "基礎"},
    {en: "After", jp: "〜の後に", cat: "基礎"},
    {en: "Until", jp: "〜まで", cat: "基礎"},
    {en: "Once", jp: "いったん〜すると", cat: "基礎"},
    {en: "Whether", jp: "〜かどうか", cat: "基礎"},
    {en: "Always", jp: "いつも", cat: "基礎"},
    {en: "Usually", jp: "たいてい", cat: "基礎"},
    {en: "Often", jp: "しばしば", cat: "基礎"},
    {en: "Sometimes", jp: "時々", cat: "基礎"},
    {en: "Rarely", jp: "めったに〜ない", cat: "基礎"},
    {en: "Never", jp: "決して〜ない", cat: "基礎"},
    {en: "Already", jp: "すでに", cat: "基礎"},
    {en: "Yet", jp: "まだ/もう", cat: "基礎"},
    {en: "Still", jp: "まだ", cat: "基礎"},
    {en: "Just", jp: "ちょうど", cat: "基礎"},
    {en: "Now", jp: "今", cat: "基礎"},
    {en: "Then", jp: "その時/それから", cat: "基礎"},
    {en: "Soon", jp: "すぐに", cat: "基礎"},
    {en: "Later", jp: "後で", cat: "基礎"},
    {en: "Ago", jp: "〜前に", cat: "基礎"},
    {en: "Today", jp: "今日", cat: "基礎"},
    {en: "Tomorrow", jp: "明日", cat: "基礎"},
    {en: "Yesterday", jp: "昨日", cat: "基礎"},
    {en: "Here", jp: "ここに", cat: "基礎"},
    {en: "There", jp: "そこに", cat: "基礎"},
    {en: "Everywhere", jp: "どこでも", cat: "基礎"},
    {en: "Somewhere", jp: "どこかで", cat: "基礎"},
    {en: "Nowhere", jp: "どこにも〜ない", cat: "基礎"},
    {en: "Very", jp: "とても", cat: "基礎"},
    {en: "Really", jp: "本当に", cat: "基礎"},
    {en: "Quite", jp: "かなり", cat: "基礎"},
    {en: "Too", jp: "〜すぎる/〜もまた", cat: "基礎"},
    {en: "So", jp: "とても/だから", cat: "基礎"},
    {en: "Enough", jp: "十分に", cat: "基礎"},
    {en: "Almost", jp: "ほとんど", cat: "基礎"},
    {en: "Nearly", jp: "ほとんど", cat: "基礎"},
    {en: "Only", jp: "〜だけ", cat: "基礎"},
    {en: "Even", jp: "〜でさえ", cat: "基礎"},
    {en: "Also", jp: "〜もまた", cat: "基礎"},
    {en: "Ideally", jp: "理想的には", cat: "基礎"},
    {en: "Actually", jp: "実際は", cat: "基礎"},
    {en: "Probably", jp: "たぶん", cat: "基礎"},
    {en: "Possibly", jp: "ことによると", cat: "基礎"},
    {en: "Especially", jp: "特に", cat: "基礎"},
    {en: "Specifically", jp: "具体的に", cat: "基礎"},
    {en: "Generally", jp: "一般的に", cat: "基礎"},
    {en: "Normally", jp: "通常は", cat: "基礎"},
    {en: "Finally", jp: "ついに", cat: "基礎"},
    {en: "Suddenly", jp: "突然", cat: "基礎"},
    {en: "Immediately", jp: "直ちに", cat: "基礎"},
    {en: "Directly", jp: "直接に", cat: "基礎"},
    {en: "Carefully", jp: "注意深く", cat: "基礎"},
    {en: "Quickly", jp: "素早く", cat: "基礎"},
    {en: "Slowly", jp: "ゆっくりと", cat: "基礎"},
    {en: "Easily", jp: "簡単に", cat: "基礎"},
    {en: "Hardly", jp: "ほとんど〜ない", cat: "基礎"},
    {en: "Lately", jp: "最近", cat: "基礎"},
    {en: "Recently", jp: "最近", cat: "基礎"},
    {en: "Currently", jp: "現在は", cat: "基礎"},
    {en: "Previously", jp: "以前は", cat: "基礎"},
    {en: "Formally", jp: "正式に", cat: "基礎"},
    {en: "Formerly", jp: "以前は", cat: "基礎"},
    {en: "Good", jp: "良い", cat: "基礎"},
    {en: "Bad", jp: "悪い", cat: "基礎"},
    {en: "Big", jp: "大きい", cat: "基礎"},
    {en: "Small", jp: "小さい", cat: "基礎"},
    {en: "Long", jp: "長い", cat: "基礎"},
    {en: "Short", jp: "短い", cat: "基礎"},
    {en: "High", jp: "高い", cat: "基礎"},
    {en: "Low", jp: "低い", cat: "基礎"},
    {en: "New", jp: "新しい", cat: "基礎"},
    {en: "Old", jp: "古い", cat: "基礎"},
    {en: "Young", jp: "若い", cat: "基礎"},
    {en: "Hot", jp: "暑い", cat: "基礎"},
    {en: "Cold", jp: "寒い", cat: "基礎"},
    {en: "Right", jp: "正しい/右", cat: "基礎"},
    {en: "Wrong", jp: "間違った", cat: "基礎"},
    {en: "Easy", jp: "簡単な", cat: "基礎"},
    {en: "Difficult", jp: "難しい", cat: "基礎"},
    {en: "Hard", jp: "硬い/難しい", cat: "基礎"},
    {en: "Soft", jp: "柔らかい", cat: "基礎"},
    {en: "Fast", jp: "速い", cat: "基礎"},
    {en: "Slow", jp: "遅い", cat: "基礎"},
    {en: "Strong", jp: "強い", cat: "基礎"},
    {en: "Weak", jp: "弱い", cat: "基礎"},
    {en: "Heavy", jp: "重い", cat: "基礎"},
    {en: "Light", jp: "軽い", cat: "基礎"},
    {en: "Dark", jp: "暗い", cat: "基礎"},
    {en: "Bright", jp: "明るい", cat: "基礎"},
    {en: "Clean", jp: "清潔な", cat: "基礎"},
    {en: "Dirty", jp: "汚い", cat: "基礎"},
    {en: "Empty", jp: "空の", cat: "基礎"},
    {en: "Full", jp: "満杯の", cat: "基礎"},
    {en: "Expensive", jp: "高価な", cat: "基礎"},
    {en: "Cheap", jp: "安価な", cat: "基礎"},
    {en: "Rich", jp: "裕福な", cat: "基礎"},
    {en: "Poor", jp: "貧しい", cat: "基礎"},
    {en: "Happy", jp: "幸せな", cat: "基礎"},
    {en: "Sad", jp: "悲しい", cat: "基礎"},
    {en: "Angry", jp: "怒った", cat: "基礎"},
    {en: "Tired", jp: "疲れた", cat: "基礎"},
    {en: "Busy", jp: "忙しい", cat: "基礎"},
    {en: "Free", jp: "自由な/暇な/無料の", cat: "基礎"},
    {en: "Safe", jp: "安全な", cat: "基礎"},
    {en: "Dangerous", jp: "危険な", cat: "基礎"},
    {en: "Same", jp: "同じ", cat: "基礎"},
    {en: "Different", jp: "違う", cat: "基礎"},
    {en: "Possible", jp: "可能な", cat: "基礎"},
    {en: "Impossible", jp: "不可能な", cat: "基礎"},
    {en: "Necessary", jp: "必要な", cat: "基礎"},
    {en: "Important", jp: "重要な", cat: "基礎"},
    {en: "Main", jp: "主な", cat: "基礎"},
    {en: "Major", jp: "主要な", cat: "基礎"},
    {en: "Minor", jp: "重要でない", cat: "基礎"},
    {en: "Real", jp: "本物の", cat: "基礎"},
    {en: "True", jp: "真実の", cat: "基礎"},
    {en: "False", jp: "偽の", cat: "基礎"},
    {en: "Public", jp: "公の", cat: "基礎"},
    {en: "Private", jp: "私的な", cat: "基礎"},
    {en: "Social", jp: "社会的な", cat: "基礎"},
    {en: "Personal", jp: "個人の", cat: "基礎"},
    {en: "National", jp: "国の", cat: "基礎"},
    {en: "International", jp: "国際的な", cat: "基礎"},
    {en: "Global", jp: "世界的な", cat: "基礎"},
    {en: "Local", jp: "地元の", cat: "基礎"},
    {en: "Available", jp: "利用できる", cat: "基礎"},
    {en: "Able", jp: "できる", cat: "基礎"},
    {en: "Capable", jp: "能力がある", cat: "基礎"},
    {en: "Responsible", jp: "責任がある", cat: "基礎"},
    {en: "Aware", jp: "気づいている", cat: "基礎"},
    {en: "Sure", jp: "確信している", cat: "基礎"},
    {en: "Certain", jp: "確かな", cat: "基礎"},
    {en: "Clear", jp: "明らかな", cat: "基礎"},
    {en: "Obvious", jp: "明白な", cat: "基礎"},
    {en: "Likely", jp: "ありそうな", cat: "基礎"},
    {en: "Unlikely", jp: "ありそうもない", cat: "基礎"},
    {en: "Due", jp: "期限が来て", cat: "基礎"},
    {en: "Ready", jp: "準備ができて", cat: "基礎"},
    {en: "Willing", jp: "いとわない", cat: "基礎"},
    {en: "Eager", jp: "熱望して", cat: "基礎"},
    {en: "Curious", jp: "好奇心の強い", cat: "基礎"},
    {en: "Serious", jp: "真剣な", cat: "基礎"},
    {en: "Various", jp: "様々な", cat: "基礎"},
    {en: "Several", jp: "いくつかの", cat: "基礎"},
    {en: "Numerous", jp: "多数の", cat: "基礎"},
    {en: "Additional", jp: "追加の", cat: "基礎"},
    {en: "Extra", jp: "余分の", cat: "基礎"},
    {en: "Further", jp: "さらなる", cat: "基礎"},
    {en: "Final", jp: "最後の", cat: "基礎"},
    {en: "Previous", jp: "前の", cat: "基礎"},
    {en: "Following", jp: "次の", cat: "基礎"},
    {en: "Next", jp: "次の", cat: "基礎"},
    {en: "Last", jp: "最後の/この前の", cat: "基礎"},
    {en: "Current", jp: "現在の", cat: "基礎"},
    {en: "Recent", jp: "最近の", cat: "基礎"},
    {en: "Future", jp: "未来の", cat: "基礎"},
    {en: "Past", jp: "過去の", cat: "基礎"},
    {en: "Modern", jp: "現代の", cat: "基礎"},
    {en: "Traditional", jp: "伝統的な", cat: "基礎"},
    {en: "Cultural", jp: "文化的な", cat: "基礎"},
    {en: "Natural", jp: "自然の", cat: "基礎"},
    {en: "Artificial", jp: "人工の", cat: "基礎"},
    {en: "Physical", jp: "身体の/物理的な", cat: "基礎"},
    {en: "Mental", jp: "精神の", cat: "基礎"},
    {en: "Medical", jp: "医療の", cat: "基礎"},
    {en: "Legal", jp: "法律の", cat: "基礎"},
    {en: "Financial", jp: "財政の", cat: "基礎"},
    {en: "Economic", jp: "経済の", cat: "基礎"},
    {en: "Political", jp: "政治の", cat: "基礎"},
    {en: "Environmental", jp: "環境の", cat: "基礎"},
    {en: "Industrial", jp: "産業の", cat: "基礎"},
    {en: "Commercial", jp: "商業の", cat: "基礎"},
    {en: "Technical", jp: "技術的な", cat: "基礎"},
    {en: "Professional", jp: "プロの", cat: "基礎"},
    {en: "Official", jp: "公式の", cat: "基礎"},
    {en: "Formal", jp: "正式な", cat: "基礎"},
    {en: "Informal", jp: "非公式な", cat: "基礎"},
    {en: "Positive", jp: "肯定的な", cat: "基礎"},
    {en: "Negative", jp: "否定的な", cat: "基礎"},
    {en: "Active", jp: "活動的な", cat: "基礎"},
    {en: "Passive", jp: "受動的な", cat: "基礎"},
    {en: "Creative", jp: "創造的な", cat: "基礎"},
    {en: "Effective", jp: "効果的な", cat: "基礎"},
    {en: "Efficient", jp: "効率的な", cat: "基礎"},
    {en: "Successful", jp: "成功した", cat: "基礎"},
    {en: "Useful", jp: "役に立つ", cat: "基礎"},
    {en: "Helpful", jp: "助けになる", cat: "基礎"},
    {en: "Suitable", jp: "適した", cat: "基礎"},
    {en: "Appropriate", jp: "適切な", cat: "基礎"},
    {en: "Correct", jp: "正しい", cat: "基礎"},
    {en: "Accurate", jp: "正確な", cat: "基礎"},
    {en: "Perfect", jp: "完璧な", cat: "基礎"},
    {en: "Excellent", jp: "優秀な", cat: "基礎"},
    {en: "Wonderful", jp: "素晴らしい", cat: "基礎"},
    {en: "Amazing", jp: "驚くべき", cat: "基礎"},
    {en: "Interesting", jp: "面白い", cat: "基礎"},
    {en: "Exciting", jp: "興奮させる", cat: "基礎"},
    {en: "Boring", jp: "退屈な", cat: "基礎"},
    {en: "Tired", jp: "疲れた", cat: "基礎"},
    {en: "Surprised", jp: "驚いた", cat: "基礎"},
    {en: "Worried", jp: "心配した", cat: "基礎"},
    {en: "Afraid", jp: "恐れて", cat: "基礎"},
    {en: "Sorry", jp: "すまなく思って", cat: "基礎"},
    {en: "Glad", jp: "うれしい", cat: "基礎"},
    {en: "Proud", jp: "誇りに思う", cat: "基礎"},
    {en: "Famous", jp: "有名な", cat: "基礎"},
    {en: "Popular", jp: "人気のある", cat: "基礎"},
    {en: "Common", jp: "共通の/普通の", cat: "基礎"},
    {en: "Normal", jp: "普通の", cat: "基礎"},
    {en: "Regular", jp: "定期的な", cat: "基礎"},
    {en: "Strange", jp: "奇妙な", cat: "基礎"},
    {en: "Unique", jp: "独特な", cat: "基礎"},
    {en: "Special", jp: "特別な", cat: "基礎"},
    {en: "General", jp: "一般的な", cat: "基礎"},
    {en: "Typical", jp: "典型的な", cat: "基礎"},
    {en: "Specific", jp: "具体的な", cat: "基礎"},
    {en: "Particular", jp: "特定の", cat: "基礎"},
    {en: "Individual", jp: "個々の", cat: "基礎"},
    {en: "Single", jp: "単一の/独身の", cat: "基礎"},
    {en: "Double", jp: "二重の", cat: "基礎"},
    {en: "Total", jp: "全体の", cat: "基礎"},
    {en: "Whole", jp: "全体の", cat: "基礎"},
    {en: "Entire", jp: "全体の", cat: "基礎"},
    {en: "Complete", jp: "完全な", cat: "基礎"},
    {en: "Partial", jp: "部分的な", cat: "基礎"},
    {en: "About", jp: "〜について", cat: "基礎"},
    {en: "Above", jp: "〜の上に", cat: "基礎"},
    {en: "Across", jp: "〜を横切って", cat: "基礎"},
    {en: "Against", jp: "〜に反対して", cat: "基礎"},
    {en: "Along", jp: "〜に沿って", cat: "基礎"},
    {en: "Among", jp: "〜の間に", cat: "基礎"},
    {en: "Around", jp: "〜の周りに", cat: "基礎"},
    {en: "At", jp: "〜に", cat: "基礎"},
    {en: "Behind", jp: "〜の後ろに", cat: "基礎"},
    {en: "Below", jp: "〜の下に", cat: "基礎"},
    {en: "Beside", jp: "〜のそばに", cat: "基礎"},
    {en: "Between", jp: "〜の間に", cat: "基礎"},
    {en: "Beyond", jp: "〜を超えて", cat: "基礎"},
    {en: "By", jp: "〜によって/〜まで", cat: "基礎"},
    {en: "Down", jp: "〜を下って", cat: "基礎"},
    {en: "During", jp: "〜の間", cat: "基礎"},
    {en: "Except", jp: "〜を除いて", cat: "基礎"},
    {en: "For", jp: "〜のために", cat: "基礎"},
    {en: "From", jp: "〜から", cat: "基礎"},
    {en: "In", jp: "〜の中に", cat: "基礎"},
    {en: "Inside", jp: "〜の内側に", cat: "基礎"},
    {en: "Into", jp: "〜の中へ", cat: "基礎"},
    {en: "Near", jp: "〜の近くに", cat: "基礎"},
    {en: "Of", jp: "〜の", cat: "基礎"},
    {en: "Off", jp: "〜から離れて", cat: "基礎"},
    {en: "On", jp: "〜の上に", cat: "基礎"},
    {en: "Out", jp: "〜の外へ", cat: "基礎"},
    {en: "Outside", jp: "〜の外側に", cat: "基礎"},
    {en: "Over", jp: "〜を越えて", cat: "基礎"},
    {en: "Past", jp: "〜を過ぎて", cat: "基礎"},
    {en: "Through", jp: "〜を通って", cat: "基礎"},
    {en: "To", jp: "〜へ", cat: "基礎"},
    {en: "Toward", jp: "〜の方へ", cat: "基礎"},
    {en: "Under", jp: "〜の下に", cat: "基礎"},
    {en: "Up", jp: "〜を上って", cat: "基礎"},
    {en: "With", jp: "〜と一緒に", cat: "基礎"},
    {en: "Within", jp: "〜以内に", cat: "基礎"},
    {en: "Without", jp: "〜なしで", cat: "基礎"},

    // ==========================================
    // 【4. 一般・旅行・生活 (TOEIC Part 1,2,7対策)】
    // ==========================================
    {en: "Airport", jp: "空港", cat: "一般"},
    {en: "Station", jp: "駅", cat: "一般"},
    {en: "Hotel", jp: "ホテル", cat: "一般"},
    {en: "Restaurant", jp: "レストラン", cat: "一般"},
    {en: "Store", jp: "店", cat: "一般"},
    {en: "Shop", jp: "店", cat: "一般"},
    {en: "Supermarket", jp: "スーパー", cat: "一般"},
    {en: "Mall", jp: "モール", cat: "一般"},
    {en: "Market", jp: "市場", cat: "一般"},
    {en: "Bank", jp: "銀行", cat: "一般"},
    {en: "Post office", jp: "郵便局", cat: "一般"},
    {en: "Library", jp: "図書館", cat: "一般"},
    {en: "School", jp: "学校", cat: "一般"},
    {en: "University", jp: "大学", cat: "一般"},
    {en: "Hospital", jp: "病院", cat: "一般"},
    {en: "Clinic", jp: "診療所", cat: "一般"},
    {en: "Park", jp: "公園", cat: "一般"},
    {en: "Garden", jp: "庭", cat: "一般"},
    {en: "Street", jp: "通り", cat: "一般"},
    {en: "Road", jp: "道路", cat: "一般"},
    {en: "Bridge", jp: "橋", cat: "一般"},
    {en: "Building", jp: "建物", cat: "一般"},
    {en: "House", jp: "家", cat: "一般"},
    {en: "Apartment", jp: "アパート", cat: "一般"},
    {en: "Room", jp: "部屋", cat: "一般"},
    {en: "Office", jp: "事務所", cat: "一般"},
    {en: "Desk", jp: "机", cat: "一般"},
    {en: "Chair", jp: "椅子", cat: "一般"},
    {en: "Table", jp: "テーブル", cat: "一般"},
    {en: "Computer", jp: "コンピュータ", cat: "一般"},
    {en: "Phone", jp: "電話", cat: "一般"},
    {en: "Internet", jp: "インターネット", cat: "一般"},
    {en: "Email", jp: "電子メール", cat: "一般"},
    {en: "Website", jp: "ウェブサイト", cat: "一般"},
    {en: "News", jp: "ニュース", cat: "一般"},
    {en: "Information", jp: "情報", cat: "一般"},
    {en: "Advice", jp: "助言", cat: "一般"},
    {en: "Suggestion", jp: "提案", cat: "一般"},
    {en: "Problem", jp: "問題", cat: "一般"},
    {en: "Issue", jp: "問題点", cat: "一般"},
    {en: "Solution", jp: "解決策", cat: "一般"},
    {en: "Result", jp: "結果", cat: "一般"},
    {en: "Cause", jp: "原因", cat: "一般"},
    {en: "Reason", jp: "理由", cat: "一般"},
    {en: "Effect", jp: "効果/影響", cat: "一般"},
    {en: "Purpose", jp: "目的", cat: "一般"},
    {en: "Goal", jp: "目標", cat: "一般"},
    {en: "Success", jp: "成功", cat: "一般"},
    {en: "Failure", jp: "失敗", cat: "一般"},
    {en: "Experience", jp: "経験", cat: "一般"},
    {en: "Opportunity", jp: "機会", cat: "一般"},
    {en: "Chance", jp: "好機", cat: "一般"},
    {en: "Way", jp: "方法/道", cat: "一般"},
    {en: "Idea", jp: "考え", cat: "一般"},
    {en: "Mind", jp: "心/精神", cat: "一般"},
    {en: "Thought", jp: "思考", cat: "一般"},
    {en: "Opinion", jp: "意見", cat: "一般"},
    {en: "View", jp: "見解/眺め", cat: "一般"},
    {en: "Point", jp: "要点", cat: "一般"},
    {en: "Case", jp: "場合/事例", cat: "一般"},
    {en: "Example", jp: "例", cat: "一般"},
    {en: "Fact", jp: "事実", cat: "一般"},
    {en: "Truth", jp: "真実", cat: "一般"},
    {en: "Lie", jp: "嘘", cat: "一般"},
    {en: "Life", jp: "生活/人生", cat: "一般"},
    {en: "Death", jp: "死", cat: "一般"},
    {en: "Health", jp: "健康", cat: "一般"},
    {en: "Body", jp: "体", cat: "一般"},
    {en: "Head", jp: "頭", cat: "一般"},
    {en: "Hand", jp: "手", cat: "一般"},
    {en: "Face", jp: "顔", cat: "一般"},
    {en: "Eye", jp: "目", cat: "一般"},
    {en: "Mouth", jp: "口", cat: "一般"},
    {en: "Foot", jp: "足", cat: "一般"},
    {en: "Water", jp: "水", cat: "一般"},
    {en: "Food", jp: "食べ物", cat: "一般"},
    {en: "Air", jp: "空気", cat: "一般"},
    {en: "Light", jp: "光", cat: "一般"},
    {en: "Sound", jp: "音", cat: "一般"},
    {en: "Music", jp: "音楽", cat: "一般"},
    {en: "Art", jp: "芸術", cat: "一般"},
    {en: "Science", jp: "科学", cat: "一般"},
    {en: "History", jp: "歴史", cat: "一般"},
    {en: "Language", jp: "言語", cat: "一般"},
    {en: "Word", jp: "単語", cat: "一般"},
    {en: "Name", jp: "名前", cat: "一般"},
    {en: "Number", jp: "数字", cat: "一般"},
    {en: "Time", jp: "時間", cat: "一般"},
    {en: "Year", jp: "年", cat: "一般"},
    {en: "Month", jp: "月", cat: "一般"},
    {en: "Week", jp: "週", cat: "一般"},
    {en: "Day", jp: "日", cat: "一般"},
    {en: "Hour", jp: "時間", cat: "一般"},
    {en: "Minute", jp: "分", cat: "一般"},
    {en: "Second", jp: "秒", cat: "一般"},
    {en: "Morning", jp: "朝", cat: "一般"},
    {en: "Afternoon", jp: "昼", cat: "一般"},
    {en: "Evening", jp: "夕方", cat: "一般"},
    {en: "Night", jp: "夜", cat: "一般"},
    {en: "Reservation", jp: "予約", cat: "一般"},
    {en: "Passenger", jp: "乗客", cat: "一般"},
    {en: "Destination", jp: "目的地", cat: "一般"},
    {en: "Luggage", jp: "手荷物", cat: "一般"},
    {en: "Baggage", jp: "手荷物", cat: "一般"},
    {en: "Suitcase", jp: "スーツケース", cat: "一般"},
    {en: "Flight attendant", jp: "客室乗務員", cat: "一般"},
    {en: "Boarding pass", jp: "搭乗券", cat: "一般"},
    {en: "Customs", jp: "税関", cat: "一般"},
    {en: "Immigration", jp: "入国審査", cat: "一般"},
    {en: "Currency exchange", jp: "両替", cat: "一般"},
    {en: "Sightseeing", jp: "観光", cat: "一般"},
    {en: "Souvenir", jp: "お土産", cat: "一般"},
    {en: "Guidebook", jp: "ガイドブック", cat: "一般"},
    {en: "Map", jp: "地図", cat: "一般"},
    {en: "Direction", jp: "方向/指示", cat: "一般"},
    {en: "Distance", jp: "距離", cat: "一般"},
    {en: "Location", jp: "場所", cat: "一般"},
    {en: "Area", jp: "地域", cat: "一般"},
    {en: "Region", jp: "地方", cat: "一般"},
    {en: "Country", jp: "国", cat: "一般"},
    {en: "City", jp: "都市", cat: "一般"},
    {en: "Town", jp: "町", cat: "一般"},
    {en: "Village", jp: "村", cat: "一般"},

    // ==========================================
    // 【5. 熟語・慣用表現 (Part 5/6対策)】
    // ==========================================
    {en: "In charge of", jp: "担当して", cat: "熟語"},
    {en: "Responsible for", jp: "責任がある", cat: "熟語"},
    {en: "Capable of", jp: "能力がある", cat: "熟語"},
    {en: "Depending on", jp: "〜次第で", cat: "熟語"},
    {en: "According to", jp: "〜によると", cat: "熟語"},
    {en: "Because of", jp: "〜のために(原因)", cat: "熟語"},
    {en: "Due to", jp: "〜のために(原因)", cat: "熟語"},
    {en: "Owing to", jp: "〜のために(原因)", cat: "熟語"},
    {en: "Thanks to", jp: "〜のおかげで", cat: "熟語"},
    {en: "Instead of", jp: "〜の代わりに", cat: "熟語"},
    {en: "In spite of", jp: "〜にもかかわらず", cat: "熟語"},
    {en: "Regardless of", jp: "〜に関係なく", cat: "熟語"},
    {en: "In addition to", jp: "〜に加えて", cat: "熟語"},
    {en: "Prior to", jp: "〜より前に", cat: "熟語"},
    {en: "Ahead of", jp: "〜より先に", cat: "熟語"},
    {en: "Apart from", jp: "〜は別として", cat: "熟語"},
    {en: "Aside from", jp: "〜は別として", cat: "熟語"},
    {en: "As for", jp: "〜については", cat: "熟語"},
    {en: "As to", jp: "〜については", cat: "熟語"},
    {en: "With regard to", jp: "〜に関して", cat: "熟語"},
    {en: "In terms of", jp: "〜の点では", cat: "熟語"},
    {en: "By means of", jp: "〜を用いて", cat: "熟語"},
    {en: "On behalf of", jp: "〜を代表して", cat: "熟語"},
    {en: "In case of", jp: "〜の場合には", cat: "熟語"},
    {en: "In the event of", jp: "〜の場合には", cat: "熟語"},
    {en: "Look forward to", jp: "楽しみに待つ", cat: "熟語"},
    {en: "Get used to", jp: "慣れる", cat: "熟語"},
    {en: "Be used to", jp: "慣れている", cat: "熟語"},
    {en: "Participate in", jp: "参加する", cat: "熟語"},
    {en: "Take part in", jp: "参加する", cat: "熟語"},
    {en: "Sign up for", jp: "申し込む", cat: "熟語"},
    {en: "Apply for", jp: "申し込む", cat: "熟語"},
    {en: "Ask for", jp: "求める", cat: "熟語"},
    {en: "Look for", jp: "探す", cat: "熟語"},
    {en: "Wait for", jp: "待つ", cat: "熟語"},
    {en: "Pay for", jp: "支払う", cat: "熟語"},
    {en: "Account for", jp: "説明する/占める", cat: "熟語"},
    {en: "Set up", jp: "設立する/設置する", cat: "熟語"},
    {en: "Call off", jp: "中止する", cat: "熟語"},
    {en: "Put off", jp: "延期する", cat: "熟語"},
    {en: "Carry out", jp: "実行する", cat: "熟語"},
    {en: "Figure out", jp: "理解する", cat: "熟語"},
    {en: "Point out", jp: "指摘する", cat: "熟語"},
    {en: "Turn out", jp: "判明する", cat: "熟語"},
    {en: "Run out of", jp: "使い果たす", cat: "熟語"},
    {en: "Deal with", jp: "対処する", cat: "熟語"},
    {en: "Cope with", jp: "対処する", cat: "熟語"},
    {en: "Keep up with", jp: "ついていく", cat: "熟語"},
    {en: "Catch up with", jp: "追いつく", cat: "熟語"},
    {en: "Come up with", jp: "思いつく", cat: "熟語"},
    {en: "Look after", jp: "世話をする", cat: "熟語"},
    {en: "Look into", jp: "調査する", cat: "熟語"},
    {en: "Go through", jp: "経験する/通過する", cat: "熟語"},
    {en: "Get over", jp: "乗り越える", cat: "熟語"},
    {en: "Turn on", jp: "つける", cat: "熟語"},
    {en: "Turn off", jp: "消す", cat: "熟語"},
    {en: "Fill in", jp: "記入する", cat: "熟語"},
    {en: "Fill out", jp: "記入する", cat: "熟語"},
    {en: "Hand in", jp: "提出する", cat: "熟語"},
    {en: "Turn in", jp: "提出する", cat: "熟語"},
    {en: "Give up", jp: "あきらめる", cat: "熟語"},
    {en: "Pick up", jp: "拾う/車で迎える", cat: "熟語"},
    {en: "Bring up", jp: "育てる/話題に出す", cat: "熟語"},
    {en: "Back up", jp: "支援する/後退する", cat: "熟語"},
    {en: "Break down", jp: "故障する", cat: "熟語"},
    {en: "Show up", jp: "現れる", cat: "熟語"},
    {en: "Check in", jp: "チェックインする", cat: "熟語"},
    {en: "Check out", jp: "チェックアウトする", cat: "熟語"},
    {en: "Hold on", jp: "待つ", cat: "熟語"},
    {en: "Hang up", jp: "電話を切る", cat: "熟語"},
    {en: "Result in", jp: "〜という結果になる", cat: "熟語"},
    {en: "Result from", jp: "〜に起因する", cat: "熟語"},
    {en: "Succeed in", jp: "成功する", cat: "熟語"},
    {en: "Focus on", jp: "集中する", cat: "熟語"},
    {en: "Concentrate on", jp: "集中する", cat: "熟語"},
    {en: "Rely on", jp: "頼る", cat: "熟語"},
    {en: "Depend on", jp: "頼る/〜次第だ", cat: "熟語"},
    {en: "Count on", jp: "当てにする", cat: "熟語"},
    {en: "Insist on", jp: "主張する", cat: "熟語"},
    {en: "Based on", jp: "基づいて", cat: "熟語"},
    {en: "Interested in", jp: "興味がある", cat: "熟語"},
    {en: "Involved in", jp: "関わっている", cat: "熟語"},
    {en: "Related to", jp: "関連している", cat: "熟語"},
    {en: "Associated with", jp: "関連している", cat: "熟語"},
    {en: "Familiar with", jp: "精通している", cat: "熟語"},
    {en: "Similar to", jp: "似ている", cat: "熟語"},
    {en: "Different from", jp: "異なっている", cat: "熟語"},
    {en: "Aware of", jp: "気づいている", cat: "熟語"},
    {en: "Afraid of", jp: "恐れている", cat: "熟語"},
    {en: "Fond of", jp: "好んでいる", cat: "熟語"},
    {en: "Full of", jp: "いっぱいの", cat: "熟語"},
    {en: "Short of", jp: "不足している", cat: "熟語"},
    {en: "Capable of", jp: "能力がある", cat: "熟語"},
    {en: "Proud of", jp: "誇りに思う", cat: "熟語"},
    {en: "Sure of", jp: "確信している", cat: "熟語"},
    {en: "Tired of", jp: "飽きている", cat: "熟語"},
    {en: "Used to", jp: "以前は〜だった", cat: "熟語"},
    {en: "Ought to", jp: "すべきだ", cat: "熟語"},
    {en: "Had better", jp: "したほうがよい", cat: "熟語"},
    {en: "Would rather", jp: "むしろ〜したい", cat: "熟語"},
    {en: "As soon as", jp: "〜するとすぐに", cat: "熟語"},
    {en: "So that", jp: "〜するために", cat: "熟語"},
    {en: "Even though", jp: "〜だけれども", cat: "熟語"},
    {en: "As if", jp: "まるで〜のように", cat: "熟語"},
    {en: "No matter", jp: "たとえ〜でも", cat: "熟語"},
    {en: "By the way", jp: "ところで", cat: "熟語"},
    {en: "For example", jp: "例えば", cat: "熟語"},
    {en: "For instance", jp: "例えば", cat: "熟語"},
    {en: "In fact", jp: "実際は", cat: "熟語"},
    {en: "In short", jp: "要するに", cat: "熟語"},
    {en: "After all", jp: "結局", cat: "熟語"},
    {en: "At first", jp: "最初は", cat: "熟語"},
    {en: "At last", jp: "ついに", cat: "熟語"},
    {en: "At least", jp: "少なくとも", cat: "熟語"},
    {en: "At once", jp: "すぐに", cat: "熟語"},
    {en: "On time", jp: "時間通りに", cat: "熟語"},
    {en: "In time", jp: "間に合って", cat: "熟語"}
];